[package]
name = "cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chubby_client = { path = "../chubby_client" }
tokio = { version = "1", features = ["full"] }